export const ROUTES = {
  MAIN_PAGE: "mainpage",
  PRODUCT_DETAIL: "products/:product_name_convert",
  USER_PAGE: "user/:name",
  BLOG_PAGE: "tin-tuc",
  MENU: "collections/:category_name/:category_id",
  CHECKOUT: "thanh-toan",
  PAYMENT_PROCESS: "thanh-toan-process",
  BLOG_DETAIL: "tin-tuc/:blog_name_convert",
  STORE_PAGE: "cua-hang",
  ABOUT_US: "ve-chung-toi",
  // routes cho admin
  ADMIN: {
    PROFILE: "profile",
    ORDER_DETAIL: "order-detail/:order_code",
    ANALYZE: "analyze",
    SHOPPING_BEHAVIOR: "shopping-behavior",
    MANAGE_PRODUCTS: "manage-products",
    MANAGE_PRODUCTS_CATEGORY: "manage-products/:category_name/:category_id",
    MANAGE_VOUCHERS: "manage-vouchers",
    MANAGE_TOPPINGS: "manage-toppings",
    MANAGE_ORDERS: "manage-orders",
    PAYMENT_HISTORY: "payment-history",
    LOGIN: "login",
  },
};
